from pathlib import Path
import re
R=Path(__file__).parent
for zh in [False,True]:
 def t(c,e): return c if zh else e
 page='zh.html' if zh else 'index.html'
 other='index.html' if zh else 'zh.html'
 blue='product-zh.html' if zh else 'product.html'
 privacy='privacy-zh.html' if zh else 'privacy.html'
 code='CN' if zh else 'EN'
 old=(R/page).read_text()
 form=re.search(r'<form.*?</form>',old,re.S).group(0)
 brief=f'brief/LiveLiva_One_Page_{code}.html'
 title=t('LiveLiva｜个人智能与共同世界','LiveLiva — Personal intelligence. Shared worlds.')
 desc=t('与你持续成长的个人AI，连接真人、地方与文化，让共同经历成为可以延续的世界。','Personal AI that grows through shared experience. A platform for people to explore, play and create living worlds together.')
 html=f'''<!doctype html>
<html lang="{'zh-CN' if zh else 'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><meta name="theme-color" content="#101915"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:image" content="https://wyonliu.github.io/LiveLiva/assets/shared-world.png"><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="editorial.css"></head>
<body><a class="skip" href="#vision">{t('跳到正文','Skip to content')}</a>
<header><a class="brand" href="{page}">LiveLiva</a><nav><a href="#vision">{t('体验','Experience')}</a><a href="#intelligence">{t('技术','Intelligence')}</a><a href="#library">{t('深入了解','Explore')}</a><a href="{other}" lang="{'en' if zh else 'zh'}">{t('EN','中文')}</a><a class="nav-contact" href="#connect">{t('一起创造','Let’s build')} ↗</a></nav></header>
<main>
<section class="hero"><img class="hero-art" src="assets/shared-world.png" alt="{t('两位朋友与Liva在山水城镇前共同构建微型世界，产品愿景概念画面','Two friends and Liva co-create a miniature world above an inhabited river valley. Product vision artwork.')}" fetchpriority="high"><div class="hero-shade"></div><div class="hero-copy"><p class="eyebrow">PERSONAL INTELLIGENCE. SHARED WORLDS.</p><h1>{t('与AI共同成长。<br>与真人共创世界。','A life with AI.<br>A world with others.')}</h1><p class="hero-description">{t('我们希望让个人AI带着共同的记忆与能力，参与生活、连接朋友，进入由人创造的鲜活世界。','Personal AI that carries your shared history into everyday life, human connection and worlds created by people.')}</p><div class="hero-actions"><a class="button ivory" href="#film"><span class="play-small">▶</span>{t('观看概念短片','Watch the concept film')}</a><a class="text-link" href="{brief}">{t('阅读一页简介','Read the brief')} ↗</a></div></div><div class="hero-bottom"><span>01 — THE LIVELIVA VISION</span><span>{t('愿景概念图／非实机画面','VISION ARTWORK / NOT GAMEPLAY')}</span><a href="#vision" aria-label="{t('继续阅读','Continue reading')}">↓</a></div></section>
<section class="intro wrap" id="vision"><p class="eyebrow">BEYOND THE CONVERSATION</p><div class="intro-grid"><h2>{t('智能的价值，<br>发生在生活之中。','Intelligence belongs<br>in the experience.')}</h2><div><p class="lead">{t('一次旅行、一场冒险、一间一起经营的小店。让AI在参与中理解你，让人与人在共同经历中建立关系。','A journey. An adventure. A small shop built with a friend. AI could build understanding through participation. People connect through shared experience.')}</p><p>{t('我们正在构建一个个人智能与互动世界平台：让记忆转化为行动，让地方与文化成为可亲历的体验，让创作者的世界承接持续的生命与关系。','We are building a platform that brings personal intelligence into interactive worlds: memory informs action, places and cultures become experiences, and creators’ worlds welcome persistent lives and relationships.')}</p></div></div><div class="principles"><div><span>01 / PERSONAL</span><h3>{t('记得，也能行动','Remember. Then act.')}</h3><p>{t('理解情境、提出行动，在你的许可下参与，而非把人固化成一组偏好。','Understand context, propose actions and participate with permission—without reducing a person to a preference profile.')}</p></div><div><span>02 / TOGETHER</span><h3>{t('让真人产生交集','Bring people together.')}</h3><p>{t('从共同兴趣走向共同经历，让智能体帮助真人相遇、协作与创造。','Turn shared interests into shared experiences. Agents help real people meet, collaborate and create.')}</p></div><div><span>03 / OPEN-ENDED</span><h3>{t('让经历能够延续','Let experience carry forward.')}</h3><p>{t('走进新世界时，保留被允许携带的身份、记忆与能力，让新的经历积累价值。','Enter new worlds with permitted identity, memories and capabilities, so new experiences build on what came before.')}</p></div></div></section>
<section class="experience"><div class="experience-image"><img src="assets/film/encounter.jpg" loading="lazy" alt="{t('影片中的个人AI与朋友共同参与的生活场景','A concept-film scene of personal AI, shared creation and a remote friend')}"></div><div class="experience-copy"><p class="eyebrow">FROM PERSONAL TO SHARED</p><h2>{t('从一个人的灵感，<br>到一起发生的故事。','A personal spark.<br>A shared story.')}</h2><p>{t('目标是让Liva协助你把一次出游的想法变成可探索的场景，邀请志趣相投的朋友，与你们共同发现、试错与创作。','Liva could help turn a travel idea into a place to explore, bring in friends with a shared interest, and participate as you discover, experiment and create.')}</p><p>{t('世界可以有山川与街巷，也可以有任务、经营、谜题与冒险。每个世界由作者定义自己的表达与规则。','A world can hold landscapes and lived-in streets, quests and small businesses, puzzles and adventures. Its author defines its expression and rules.')}</p><span class="caption">{t('目标体验；画面来自产品愿景概念片。','Intended experience. Image from the product concept film.')}</span></div></section>
<section class="film-section wrap" id="film"><div class="section-heading"><div><p class="eyebrow">SEE THE POSSIBILITY</p><h2>{t('一起进入LiveLiva。','Step into LiveLiva.')}</h2></div><p>{t('一部概念短片，呈现我们希望创造的体验。','A concept film of the experience we aim to build.')}</p></div><div class="film-frame"><video controls playsinline preload="none" poster="assets/film/encounter.jpg" aria-label="LiveLiva concept film"><source src="https://wyonliu.github.io/CaptainCast/liveliva/assets/video/liveliva-concept-v7-web.mp4" type="video/mp4"></video><button class="film-launch" type="button"><span class="play-circle">▶</span><span>{t('播放概念短片','PLAY CONCEPT FILM')}</span></button></div><div class="under-film"><span>{t('产品愿景概念片 · 非实机演示','PRODUCT VISION · NOT A GAMEPLAY DEMO')}</span><a href="https://wyonliu.github.io/CaptainCast/liveliva/">{t('听创始人讲述背后的思考','Hear the thinking behind LiveLiva')} ↗</a></div></section>
<section class="intelligence" id="intelligence"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">THE INTELLIGENCE ARCHITECTURE</p><h2>{t('有记忆的生命。<br>有后果的世界。','Lives with memory.<br>Worlds with consequences.')}</h2></div><p>{t('从模型生成走向可以持续参与的系统，需要把理解、行动、规则和学习清楚地连接起来。','Persistent participation requires more than generation: understanding, action, rules and learning must work together.')}</p></div><div class="system-grid"><article><span class="system-no">I</span><h3>{t('个人智能','Personal intelligence')}</h3><p>{t('身份、记忆与情境理解形成行动建议。人可以纠正AI的理解，并决定它被允许做什么。','Identity, memory and context inform proposed actions. People can correct the AI’s understanding and control what it may do.')}</p><small>NUWA / IDENTITY · MEMORY · INTENT</small></article><article><span class="system-no">II</span><h3>{t('空间与世界智能','Spatial & world intelligence')}</h3><p>{t('生成可互动的场景，预测行动后果；世界运行层执行权限与规则，以实际回执更新共享状态。','Generate interactive scenes and predict consequences. A world runtime enforces permissions and rules, updating shared state from actual outcomes.')}</p><small>PANGU + FUXI / CREATE · ACT · VERIFY</small></article><article><span class="system-no">III</span><h3>{t('持续学习与RSI','Continual learning & RSI')}</h3><p>{t('研究跨经历保留与迁移能力，以及学习方法自身的改进。以独立任务、等预算比较与回退机制验证收益。','Research capability retention and transfer, and improvements to the learning process itself. Test gains on held-out tasks, under equal budgets, with rollback.')}</p><small>RESEARCH / RETAIN · TRANSFER · IMPROVE</small></article></div><div class="architecture-link"><p>{t('模型的推测与世界已发生的事实分开记录。技术目标与当前证据分开呈现。','Model predictions remain distinct from recorded events. Technical ambition remains distinct from current evidence.')}</p><a href="{blue}">{t('阅读技术蓝图与验证范围','Explore the blueprint & evidence')} ↗</a></div><details class="architecture-details"><summary>{t('展开系统总图','View the system map')} <span>＋</span></summary><img src="brief/LiveLiva_Architecture_{code}.svg" loading="lazy" alt="{t('LiveLiva系统逻辑总图','LiveLiva system architecture')}"></details><div class="evidence"><span>{t('当前阶段','CURRENT STAGE')}</span><p>{t('已用本地合成账户完成协议原型验证：身份延续、状态冲突处理、权限撤回与重启恢复。真人使用效果、跨世界学习收益与创作者供给仍待验证。','Local protocol tests with synthetic accounts cover identity continuity, state conflicts, permission revocation and restart recovery. Human use, cross-world learning gains and independent creator supply remain to be validated.')}</p></div></div></section>
<section class="platform wrap"><p class="eyebrow">A PLATFORM FOR HUMAN CREATION</p><div class="intro-grid"><h2>{t('让更多人的世界，<br>被亲历。','Worlds worth making.<br>Lives worth sharing.')}</h2><div><p class="lead">{t('一个地方的文化，一个人的想象，一群人的日常，都可以成为共同参与的世界。','The culture of a place. The imagination of an author. The everyday life of a community. Each can become a world people participate in.')}</p><p>{t('先做出值得回访的首作，再让独立作者创造第二个世界，验证持续的AI生命与真人关系能否带来新的参与。拟议商业路径包括付费体验、订阅与表达性道具，并支持作者分益。','Start with an experience worth returning to. Then support a second world from an independent author, testing whether persistent AI lives and human relationships motivate participation. Proposed revenue includes paid experiences, subscriptions and expressive items, with creator revenue sharing.')}</p></div></div></section>
<section class="founder wrap" id="founder"><div class="founder-name"><p class="eyebrow">THE FOUNDER</p><h2>Wyon Liu</h2><p>刘怀洋</p><a href="https://wyonliu.github.io/cv/">{t('查看完整履历','Full background')} ↗</a></div><div class="founder-story"><h3>{t('从游戏引擎与空间计算，<br>到AI产品与公司经营。','From game engines and spatial computing<br>to AI products and company building.')}</h3><p>{t('北京大学计算机本硕。悉见创始人，后任贝壳创新负责人、千丁CTO。经历覆盖游戏引擎、空间智能、交互式AI角色、产品商业化与团队经营。','Peking University CS, bachelor’s and master’s. Founder of Seengene; later led innovation at Beike and served as QianDing CTO. Experience spans game engines, spatial intelligence, interactive AI characters, commercialization and team building.')}</p><div class="credentials"><div><b>{t('近亿元','~RMB100M')}</b><span>{t('悉见融资','Seengene capital raised')}</span></div><div><b>{t('百人','100')}</b><span>{t('创业团队','Team members')}</span></div><div><b>{t('数千万级','Tens of millions')}</b><span>{t('悉见收入（人民币）','Seengene revenue / RMB')}</span></div></div><small>{t('以上为过往公司成果，依据公开履历；不计作LiveLiva业绩。','Past-company outcomes from the public CV; not LiveLiva traction.')}</small></div></section>
<section class="library wrap" id="library"><div class="section-heading"><div><p class="eyebrow">THE READING ROOM</p><h2>{t('从一分钟，到深入交流。','From a first look<br>to a deeper conversation.')}</h2></div></div><div class="library-grid">{''.join(f'<a href="{url}"><span>{tag}</span><h3>{name}</h3><p>{description}</p><b>↗</b></a>' for tag,name,description,url in [('01 / BRIEF',t('一页简介','The one-page brief'),t('产品主张、技术方向与合作目标。','The product thesis, technology and partnership.'),brief),('02 / BLUEPRINT',t('产品与技术蓝图','Product & technology'),t('系统机制、验证证据与下一步。','System mechanisms, evidence and next steps.'),blue),('03 / CAPTAINCAST',t('创始人深度讲述','The founder’s perspective'),t('38分钟中文音频与图文：为什么做LiveLiva。','38-minute Chinese audio and illustrated article: why LiveLiva.'),'https://wyonliu.github.io/CaptainCast/liveliva/')])}</div></section>
<section class="connect" id="connect"><div class="wrap"><p class="eyebrow">INVESTMENT / STRATEGIC INCUBATION</p><div class="connect-grid"><h2>{t('一起把它<br>带进现实。','Let’s bring it<br>to life.')}</h2><div><p class="lead">{t('寻找愿意共同定义下一代消费级AI体验的投资人与平台伙伴。','Seeking investors and platform partners to build the next generation of consumer AI experiences.')}</p><p>{t('由刘怀洋负责产品、技术与团队，结合伙伴的游戏制作、创作者与分发资源，完成首作和第二作者世界的验证。','Wyon leads product, technology and team formation. Partners can bring game production, creators and distribution to validate the first experience and a second author’s world.')}</p><div class="contact-links"><a href="mailto:wyonliu@gmail.com">wyonliu@gmail.com ↗</a><a href="https://www.linkedin.com/in/wyonliu/">LinkedIn ↗</a></div></div></div><details class="contact-details"><summary>{t('发送私密留言','Send a private message')} <span>＋</span></summary>{form}</details></div></section>
</main><footer class="wrap"><a class="brand" href="{page}">LiveLiva</a><span>© 2026 / {t('早期项目','EARLY-STAGE PROJECT')}</span><a href="{privacy}">{t('隐私与统计设置','Privacy & analytics')}</a><a href="{other}">{t('ENGLISH','中文')}</a></footer><script src="config.js"></script><script src="site.js" defer></script><script src="editorial.js" defer></script></body></html>'''
 (R/page).write_text(html)
